openapi: 3.0.0
info:
  title: Redis Cluster sample app API
  version: 1.0.0
  description: API endpoints to interact with a Redis cluster
servers:
  - url: http://localhost:5000
paths:
  /key:
    post:
      summary: Create a key-value pair in Redis cluster
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: string
              required:
                - key
                - value
      responses:
        '200':
          description: Key created successfully
        '400':
          description: Bad request
    put:
      summary: Update the value of a key in Redis cluster
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                value:
                  type: string
              required:
                - key
                - value
      responses:
        '200':
          description: Value of key updated successfully
        '400':
          description: Bad request
        '404':
          description: Key not found
    get:
      summary: Get the value of a key from Redis cluster
      parameters:
        - in: query
          name: key
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
        '400':
          description: Bad request
        '404':
          description: Key not found
    delete:
      summary: Delete a key from Redis cluster
      parameters:
        - in: query
          name: key
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Key deleted successfully
        '400':
          description: Bad request
        '404':
          description: Key not found
